# Generated by Django 4.2.5 on 2023-09-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appshoperfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
